import turtle
s= turtle.getscreen()
t = turtle.Turtle()
turtle.title("Mi pequeña tortuga")
t.shape("turtle")
turtle.bgcolor("orange")
t.fillcolor("white")
t.pencolor("white")
t.shapesize(3,3,3)
t.pensize(5)
t.speed(2)
t.begin_fill()
t.fd(100)
t.fd(100)
t.speed(4)
t.rt(90)
t.fd(100)
t.speed(5)
t.rt(90)
t.speed(1)
t.fd(100)
t.fd(100)
t.rt(90)
t.fd(100)
t.end_fill()
t.begin_fill()
t.speed(3)
t.circle(100)
t.end_fill()
t.dot(300)
p= turtle.Turtle()
p.pen(pencolor="purple", fillcolor="orange", pensize=80, speed=9)
p.begin_fill()
p.circle(90)
p.end_fill()
t.speed(1)
t.stamp()
t.fd(50)
t.stamp()
t.fd(50)
t.stamp()
t.rt(200)
t.fd(100)
t.stamp()
t.rt(100)
p.clear()
t.clear()
turtle.bgcolor("magenta")
c = t.clone()
t.color("green")
c.color("yellow")
t.circle(80)
c.circle(60)

import turtle
t = turtle.Turtle()
for i in range(4):
    t.fd(100)
    t.rt(90)
    